# Generated by Django 5.2.16 on 2026-07-23 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('HIGH_AMOUNT', 'Amount above threshold'), ('VELOCITY', 'Too many transactions in a short window'), ('UNUSUAL_LOCATION', 'Location differs from account history'), ('ODD_HOURS', 'Transaction during odd hours')], max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=25, help_text='Points added to risk_score when this rule fires')),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('velocity_window_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('velocity_max_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('odd_hours_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('odd_hours_end', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionrule')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='transactions.transaction')),
            ],
        ),
    ]
