# Generated by Django 6.0.7 on 2026-07-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='code',
            field=models.CharField(choices=[('HIGH_AMOUNT', 'Amount above threshold'), ('VELOCITY', 'Too many transactions in a short window'), ('UNUSUAL_LOCATION', 'Location differs from account history'), ('ODD_HOURS', 'Transaction during odd hours'), ('BEHAVIORAL_ANOMALY', 'Transaction differs from recent account behavior')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='AccountBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('common_location', models.CharField(blank=True, max_length=100)),
                ('common_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to='transactions.account')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
