# Generated by Django 6.0.7 on 2026-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=10000.0, help_text='Transactions above this amount will trigger a High Severity alert.', max_digits=10)),
                ('max_velocity_count', models.IntegerField(default=5, help_text='Max allowed transactions within the velocity timeframe.')),
                ('velocity_timeframe_seconds', models.IntegerField(default=30, help_text='Timeframe in seconds to check transaction velocity.')),
            ],
            options={
                'verbose_name': 'Fraud Rule Configuration',
                'verbose_name_plural': 'Fraud Rule Configurations',
            },
        ),
    ]
