# Generated by Django 5.2.16 on 2026-07-23 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('holder_name', models.CharField(max_length=150)),
                ('usual_location', models.CharField(help_text='Typical city/region this account transacts from, e.g. Kampala', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], default='TRANSFER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(help_text='City/region the transaction originated from', max_length=100)),
                ('counterparty', models.CharField(blank=True, help_text='Recipient or merchant, if applicable', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('CLEARED', 'Cleared'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0-100 score assigned by the detection engine')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.account')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'timestamp'], name='transaction_account_9b28bc_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx')],
            },
        ),
    ]
